/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponse } from './userResponse';
import type { AuthTokensResponse } from './authTokensResponse';

export interface AuthResponse {
  user: UserResponse;
  tokens: AuthTokensResponse;
}
