/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type CountryList200Item = {
  id: string;
  name: string;
  /** @nullable */
  native: string | null;
};
