/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type CreateOrganization201Data = {
  id: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
};
