/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type CreateRole500Code = typeof CreateRole500Code[keyof typeof CreateRole500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRole500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
