/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRole403Code } from './createRole403Code';

export type CreateRole403 = {
  type: string;
  success: boolean;
  code: CreateRole403Code;
  message: string;
};
