/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRole201Data } from './createRole201Data';

export type CreateRole201 = {
  data: CreateRole201Data;
  success: boolean;
};
