/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRole409Code } from './createRole409Code';

export type CreateRole409 = {
  type: string;
  success: boolean;
  code: CreateRole409Code;
  message: string;
};
