/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganization403Code } from './createOrganization403Code';

export type CreateOrganization403 = {
  type: string;
  success: boolean;
  code: CreateOrganization403Code;
  message: string;
};
