/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type CreateOrganization403Code = typeof CreateOrganization403Code[keyof typeof CreateOrganization403Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateOrganization403Code = {
  MODULE_CREATION_LIMIT_EXCEEDED: 'MODULE_CREATION_LIMIT_EXCEEDED',
} as const;
