/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRole500Type } from './createRole500Type';
import type { CreateRole500Code } from './createRole500Code';

export type CreateRole500 = {
  success: boolean;
  type: CreateRole500Type;
  code: CreateRole500Code;
  message: string;
};
