/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRoleBodyPermissionsItem } from './createRoleBodyPermissionsItem';

export type CreateRoleBody = {
  name: string;
  /** @nullable */
  description: string | null;
  permissions: CreateRoleBodyPermissionsItem[];
};
