/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type CreateRole409Code = typeof CreateRole409Code[keyof typeof CreateRole409Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRole409Code = {
  MODULE_NAME_CONFLICT: 'MODULE_NAME_CONFLICT',
} as const;
