/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type CreateOrganization409Code = typeof CreateOrganization409Code[keyof typeof CreateOrganization409Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateOrganization409Code = {
  MODULE_NAME_CONFLICT: 'MODULE_NAME_CONFLICT',
} as const;
