/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRoleBodyPermissionsItem } from './createRoleBodyPermissionsItem';

export type CreateRoleBody = {
  name: string;
  /** @nullable */
  description: string | null;
  isSystem: boolean;
  priority: number;
  /** @nullable */
  expiresAt: string | null;
  permissions: CreateRoleBodyPermissionsItem[];
};
