/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type CreateOrganization500Code = typeof CreateOrganization500Code[keyof typeof CreateOrganization500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateOrganization500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
