/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganization201Data } from './createOrganization201Data';

export type CreateOrganization201 = {
  data: CreateOrganization201Data;
  success: boolean;
};
