/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type CreateRole500Type = typeof CreateRole500Type[keyof typeof CreateRole500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRole500Type = {
  server: 'server',
} as const;
