/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganization409Code } from './createOrganization409Code';

export type CreateOrganization409 = {
  type: string;
  success: boolean;
  code: CreateOrganization409Code;
  message: string;
};
