/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type CreateRole403Code = typeof CreateRole403Code[keyof typeof CreateRole403Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRole403Code = {
  MODULE_CREATION_LIMIT_EXCEEDED: 'MODULE_CREATION_LIMIT_EXCEEDED',
} as const;
