/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type CreateOrganization500Type = typeof CreateOrganization500Type[keyof typeof CreateOrganization500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateOrganization500Type = {
  server: 'server',
} as const;
