/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganization500Type } from './createOrganization500Type';
import type { CreateOrganization500Code } from './createOrganization500Code';

export type CreateOrganization500 = {
  success: boolean;
  type: CreateOrganization500Type;
  code: CreateOrganization500Code;
  message: string;
};
