/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiRegionStates500Type } from './getApiRegionStates500Type';
import type { GetApiRegionStates500Code } from './getApiRegionStates500Code';

export type GetApiRegionStates500 = {
  success: boolean;
  type: GetApiRegionStates500Type;
  code: GetApiRegionStates500Code;
  message: string;
};
