/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiRegionStates500Type = typeof GetApiRegionStates500Type[keyof typeof GetApiRegionStates500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiRegionStates500Type = {
  server: 'server',
} as const;
