/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiRegionStates500Code = typeof GetApiRegionStates500Code[keyof typeof GetApiRegionStates500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiRegionStates500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
