/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrganizationById200Data } from './getOrganizationById200Data';

export type GetOrganizationById200 = {
  data: GetOrganizationById200Data;
  success: boolean;
};
