/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type GetOrganizationById500Code = typeof GetOrganizationById500Code[keyof typeof GetOrganizationById500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrganizationById500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
