/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type GetOrganizationById500Type = typeof GetOrganizationById500Type[keyof typeof GetOrganizationById500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrganizationById500Type = {
  server: 'server',
} as const;
