/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrganizationById200DataAnyOf } from './getOrganizationById200DataAnyOf';
import type { GetOrganizationById200DataAnyOfTwo } from './getOrganizationById200DataAnyOfTwo';

export type GetOrganizationById200Data = GetOrganizationById200DataAnyOf | GetOrganizationById200DataAnyOfTwo;
