/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrganizationById500Type } from './getOrganizationById500Type';
import type { GetOrganizationById500Code } from './getOrganizationById500Code';

export type GetOrganizationById500 = {
  success: boolean;
  type: GetOrganizationById500Type;
  code: GetOrganizationById500Code;
  message: string;
};
