/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type GetPermissionsMatrix200DataResourcesItemName = typeof GetPermissionsMatrix200DataResourcesItemName[keyof typeof GetPermissionsMatrix200DataResourcesItemName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPermissionsMatrix200DataResourcesItemName = {
  USER: 'USER',
  ROLE: 'ROLE',
  ITEM: 'ITEM',
  INVOICE: 'INVOICE',
  CUSTOMER: 'CUSTOMER',
  SUPPLIER: 'SUPPLIER',
  PURCHASE_ORDER: 'PURCHASE_ORDER',
  SALES_ORDER: 'SALES_ORDER',
  WAREHOUSE: 'WAREHOUSE',
  ORGANIZATION: 'ORGANIZATION',
  REPORT: 'REPORT',
} as const;
