/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPermissionsMatrix200DataResourcesItemName } from './getPermissionsMatrix200DataResourcesItemName';

export type GetPermissionsMatrix200DataResourcesItem = {
  id: string;
  name: GetPermissionsMatrix200DataResourcesItemName;
  /** @nullable */
  description: string | null;
};
