/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPermissionsMatrix200Data } from './getPermissionsMatrix200Data';

export type GetPermissionsMatrix200 = {
  data: GetPermissionsMatrix200Data;
  success: boolean;
};
