/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type GetPermissionsMatrix200DataActionsItemName = typeof GetPermissionsMatrix200DataActionsItemName[keyof typeof GetPermissionsMatrix200DataActionsItemName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPermissionsMatrix200DataActionsItemName = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  EXPORT: 'EXPORT',
  IMPORT: 'IMPORT',
  SHARE: 'SHARE',
  ARCHIVE: 'ARCHIVE',
  RESTORE: 'RESTORE',
} as const;
