/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type GetPermissionsMatrix200DataPermissionsItem = {
  id: string;
  actionId: string;
  resourceId: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  category: string | null;
  isDangerous: boolean;
};
