/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPermissionsMatrix200DataActionsItem } from './getPermissionsMatrix200DataActionsItem';
import type { GetPermissionsMatrix200DataResourcesItem } from './getPermissionsMatrix200DataResourcesItem';
import type { GetPermissionsMatrix200DataPermissionsItem } from './getPermissionsMatrix200DataPermissionsItem';

export type GetPermissionsMatrix200Data = {
  actions: GetPermissionsMatrix200DataActionsItem[];
  resources: GetPermissionsMatrix200DataResourcesItem[];
  permissions: GetPermissionsMatrix200DataPermissionsItem[];
};
