/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPermissionsMatrix200DataActionsItemName } from './getPermissionsMatrix200DataActionsItemName';

export type GetPermissionsMatrix200DataActionsItem = {
  id: string;
  name: GetPermissionsMatrix200DataActionsItemName;
  /** @nullable */
  description: string | null;
};
