/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type GetRoleById500Code = typeof GetRoleById500Code[keyof typeof GetRoleById500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoleById500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
