/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { GetRoleById200DataAnyOf } from './getRoleById200DataAnyOf';
import type { GetRoleById200DataAnyOfTwo } from './getRoleById200DataAnyOfTwo';

export type GetRoleById200Data = GetRoleById200DataAnyOf | GetRoleById200DataAnyOfTwo;
