/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type GetRoleById200DataAnyOf = {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  isSystem: boolean;
  priority: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  expiresAt: string | null;
  organizationId: string;
};
