/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { GetRoleById500Type } from './getRoleById500Type';
import type { GetRoleById500Code } from './getRoleById500Code';

export type GetRoleById500 = {
  success: boolean;
  type: GetRoleById500Type;
  code: GetRoleById500Code;
  message: string;
};
