/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type GetRoleById500Type = typeof GetRoleById500Type[keyof typeof GetRoleById500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoleById500Type = {
  server: 'server',
} as const;
