/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { GetRoleById200DataAnyOf } from './getRoleById200DataAnyOf';
import type { GetRoleById200DataAnyOfThree } from './getRoleById200DataAnyOfThree';

export type GetRoleById200Data = GetRoleById200DataAnyOf | GetRoleById200DataAnyOfThree;
