/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { GetRoleById200DataAnyOfRolePermissionsItem } from './getRoleById200DataAnyOfRolePermissionsItem';

export type GetRoleById200DataAnyOf = {
  id: string;
  name: string;
  rolePermissions: GetRoleById200DataAnyOfRolePermissionsItem[];
};
