/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { GetRoleById200Data } from './getRoleById200Data';

export type GetRoleById200 = {
  data: GetRoleById200Data;
  success: boolean;
};
