/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponse } from './userResponse';

export type IsAuthenticated200 = {
  data: UserResponse;
  success: boolean;
};
