/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { IsAuthenticated401Code } from './isAuthenticated401Code';

export type IsAuthenticated401 = {
  type: string;
  success: boolean;
  code: IsAuthenticated401Code;
  message: string;
};
