/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type IsAuthenticated401Code = typeof IsAuthenticated401Code[keyof typeof IsAuthenticated401Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IsAuthenticated401Code = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
} as const;
