/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { IsAuthenticated500Type } from './isAuthenticated500Type';
import type { IsAuthenticated500Code } from './isAuthenticated500Code';

export type IsAuthenticated500 = {
  success: boolean;
  type: IsAuthenticated500Type;
  code: IsAuthenticated500Code;
  message: string;
};
