/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type IsAuthenticated500Code = typeof IsAuthenticated500Code[keyof typeof IsAuthenticated500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IsAuthenticated500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
