/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type IsAuthenticated500Type = typeof IsAuthenticated500Type[keyof typeof IsAuthenticated500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IsAuthenticated500Type = {
  server: 'server',
} as const;
