/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { LocalRegisterInputIdentifier } from './localRegisterInputIdentifier';

export interface LocalRegisterInput {
  identifier: LocalRegisterInputIdentifier;
  /**
   * @minLength 8
   * @maxLength 20
   */
  password: string;
  /** @minLength 1 */
  name: string;
}
