/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { LocalRegisterInputIdentifier } from './localRegisterInputIdentifier';

export interface LocalRegisterInput {
  identifier: LocalRegisterInputIdentifier;
  password: string;
  name: string;
}
