/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { Login400Code } from './login400Code';

export type Login400 = {
  type: string;
  success: boolean;
  code: Login400Code;
  message: string;
};
