/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type Login500Type = typeof Login500Type[keyof typeof Login500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Login500Type = {
  server: 'server',
} as const;
