/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { Login401Code } from './login401Code';

export type Login401 = {
  type: string;
  success: boolean;
  code: Login401Code;
  message: string;
};
