/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { Login500Type } from './login500Type';
import type { Login500Code } from './login500Code';

export type Login500 = {
  success: boolean;
  type: Login500Type;
  code: Login500Code;
  message: string;
};
