/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthResponse } from './authResponse';

export type Login200 = {
  data: AuthResponse;
  success: boolean;
};
