/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type Login400Code = typeof Login400Code[keyof typeof Login400Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Login400Code = {
  AUTH_LOGIN_USER_PASSWORD_NOT_SET: 'AUTH_LOGIN_USER_PASSWORD_NOT_SET',
} as const;
