/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type Login500Code = typeof Login500Code[keyof typeof Login500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Login500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
