/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type Login401Code = typeof Login401Code[keyof typeof Login401Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Login401Code = {
  AUTH_LOGIN_INCORRECT_CREDENTIALS: 'AUTH_LOGIN_INCORRECT_CREDENTIALS',
} as const;
