/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { Logout500Type } from './logout500Type';
import type { Logout500Code } from './logout500Code';

export type Logout500 = {
  success: boolean;
  type: Logout500Type;
  code: Logout500Code;
  message: string;
};
