/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type Logout500Type = typeof Logout500Type[keyof typeof Logout500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Logout500Type = {
  server: 'server',
} as const;
