/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type Logout500Code = typeof Logout500Code[keyof typeof Logout500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Logout500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
