/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationList200DataItem } from './organizationList200DataItem';

export type OrganizationList200 = {
  data: OrganizationList200DataItem[];
  success: boolean;
};
