/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type OrganizationList500Code = typeof OrganizationList500Code[keyof typeof OrganizationList500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrganizationList500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
