/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type OrganizationList500Type = typeof OrganizationList500Type[keyof typeof OrganizationList500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrganizationList500Type = {
  server: 'server',
} as const;
