/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationList500Type } from './organizationList500Type';
import type { OrganizationList500Code } from './organizationList500Code';

export type OrganizationList500 = {
  success: boolean;
  type: OrganizationList500Type;
  code: OrganizationList500Code;
  message: string;
};
