/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type OrganizationList200DataItem = {
  id: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /**
   * @minLength 5
   * @maxLength 500
   * @nullable
   */
  description?: string | null;
  updatedAt: string;
};
