/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type RefreshToken500Code = typeof RefreshToken500Code[keyof typeof RefreshToken500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefreshToken500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
