/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { RefreshToken500Type } from './refreshToken500Type';
import type { RefreshToken500Code } from './refreshToken500Code';

export type RefreshToken500 = {
  success: boolean;
  type: RefreshToken500Type;
  code: RefreshToken500Code;
  message: string;
};
