/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type RefreshToken500Type = typeof RefreshToken500Type[keyof typeof RefreshToken500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefreshToken500Type = {
  server: 'server',
} as const;
