/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { RefreshToken401Code } from './refreshToken401Code';

export type RefreshToken401 = {
  type: string;
  success: boolean;
  code: RefreshToken401Code;
  message: string;
};
