/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type RoleList500Code = typeof RoleList500Code[keyof typeof RoleList500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleList500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
