/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { RoleList200Data } from './roleList200Data';

export type RoleList200 = {
  data: RoleList200Data;
  success: boolean;
};
