/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type RoleList200DataListItem = {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  updatedAt: string;
};
