/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type RoleList500Type = typeof RoleList500Type[keyof typeof RoleList500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleList500Type = {
  server: 'server',
} as const;
