/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { RoleList500Type } from './roleList500Type';
import type { RoleList500Code } from './roleList500Code';

export type RoleList500 = {
  success: boolean;
  type: RoleList500Type;
  code: RoleList500Code;
  message: string;
};
