/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { RoleList200DataListItem } from './roleList200DataListItem';

export type RoleList200Data = {
  list: RoleList200DataListItem[];
  /** @minimum 0 */
  totalCount: number;
  /** @minimum 0 */
  totalPages: number;
};
