/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type SignUp409Code = typeof SignUp409Code[keyof typeof SignUp409Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignUp409Code = {
  AUTH_SIGN_UP_USER_EXIST: 'AUTH_SIGN_UP_USER_EXIST',
} as const;
