/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { SignUp409Code } from './signUp409Code';

export type SignUp409 = {
  type: string;
  success: boolean;
  code: SignUp409Code;
  message: string;
};
