/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { SignUp500Type } from './signUp500Type';
import type { SignUp500Code } from './signUp500Code';

export type SignUp500 = {
  success: boolean;
  type: SignUp500Type;
  code: SignUp500Code;
  message: string;
};
