/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type SignUp500Code = typeof SignUp500Code[keyof typeof SignUp500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignUp500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
