/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type SignUp500Type = typeof SignUp500Type[keyof typeof SignUp500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignUp500Type = {
  server: 'server',
} as const;
