/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type SocialLogingoogleParams = {
/**
 * OAuth authorization code
 * @minLength 1
 */
code: string;
state?: string;
};
