/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { StateList500Type } from './stateList500Type';
import type { StateList500Code } from './stateList500Code';

export type StateList500 = {
  success: boolean;
  type: StateList500Type;
  code: StateList500Code;
  message: string;
};
