/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type StateList500Code = typeof StateList500Code[keyof typeof StateList500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StateList500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
