/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type StateList500Type = typeof StateList500Type[keyof typeof StateList500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StateList500Type = {
  server: 'server',
} as const;
