/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type TokenRefresh500Code = typeof TokenRefresh500Code[keyof typeof TokenRefresh500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenRefresh500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
