/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { TokenRefresh401Code } from './tokenRefresh401Code';

export type TokenRefresh401 = {
  type: string;
  success: boolean;
  code: TokenRefresh401Code;
  message: string;
};
