/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type TokenRefresh401Code = typeof TokenRefresh401Code[keyof typeof TokenRefresh401Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenRefresh401Code = {
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
} as const;
