/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { TokenRefresh500Type } from './tokenRefresh500Type';
import type { TokenRefresh500Code } from './tokenRefresh500Code';

export type TokenRefresh500 = {
  success: boolean;
  type: TokenRefresh500Type;
  code: TokenRefresh500Code;
  message: string;
};
