/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type TokenRefresh500Type = typeof TokenRefresh500Type[keyof typeof TokenRefresh500Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenRefresh500Type = {
  server: 'server',
} as const;
