/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateRole200Data } from './updateRole200Data';

export type UpdateRole200 = {
  data: UpdateRole200Data;
  success: boolean;
};
