/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateRole409Code } from './updateRole409Code';

export type UpdateRole409 = {
  type: string;
  success: boolean;
  code: UpdateRole409Code;
  message: string;
};
