/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOrganization409Code } from './updateOrganization409Code';

export type UpdateOrganization409 = {
  type: string;
  success: boolean;
  code: UpdateOrganization409Code;
  message: string;
};
