/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateOrganization200Data = {
  id: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /**
   * @minLength 5
   * @maxLength 500
   * @nullable
   */
  description?: string | null;
  /** @nullable */
  industryCategoryId?: string | null;
  /** @nullable */
  fiscalYearPatternId?: string | null;
  stateId: string;
  /** @nullable */
  inventoryStartDate: string | null;
  ownerId: string;
  /**
   * @minLength 5
   * @maxLength 255
   * @nullable
   */
  address?: string | null;
  /**
   * @minLength 3
   * @maxLength 10
   * @nullable
   */
  zipCode?: string | null;
  /** @nullable */
  createdAt: string | null;
  /** @nullable */
  updatedAt: string | null;
};
