/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateRoleBodyPermissionsItem } from './updateRoleBodyPermissionsItem';

export type UpdateRoleBody = {
  name?: string;
  /** @nullable */
  description?: string | null;
  permissions?: UpdateRoleBodyPermissionsItem[];
};
