/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateOrganization409Code = typeof UpdateOrganization409Code[keyof typeof UpdateOrganization409Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateOrganization409Code = {
  MODULE_NAME_CONFLICT: 'MODULE_NAME_CONFLICT',
} as const;
