/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateRole500Code = typeof UpdateRole500Code[keyof typeof UpdateRole500Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRole500Code = {
  SERVER_ERROR: 'SERVER_ERROR',
} as const;
