/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateRole409Code = typeof UpdateRole409Code[keyof typeof UpdateRole409Code];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRole409Code = {
  MODULE_NAME_CONFLICT: 'MODULE_NAME_CONFLICT',
} as const;
