/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOrganization200Data } from './updateOrganization200Data';

export type UpdateOrganization200 = {
  data: UpdateOrganization200Data;
  success: boolean;
};
