/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateRole500Type } from './updateRole500Type';
import type { UpdateRole500Code } from './updateRole500Code';

export type UpdateRole500 = {
  success: boolean;
  type: UpdateRole500Type;
  code: UpdateRole500Code;
  message: string;
};
