/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  LocalRegisterInput,
  SignUp201,
  SignUp409,
  SignUp500
} from './model';

import { customInstance } from './mutator/custom-instance';
import type { ErrorType } from './mutator/custom-instance';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const signUp = (
    localRegisterInput: LocalRegisterInput,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SignUp201>(
      {url: `/api/auth//sign-up`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: localRegisterInput, signal
    },
      options);
    }
  


export const getSignUpMutationOptions = <TError = ErrorType<SignUp409 | SignUp500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError,{data: LocalRegisterInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError,{data: LocalRegisterInput}, TContext> => {

const mutationKey = ['signUp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signUp>>, {data: LocalRegisterInput}> = (props) => {
          const {data} = props ?? {};

          return  signUp(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignUpMutationResult = NonNullable<Awaited<ReturnType<typeof signUp>>>
    export type SignUpMutationBody = LocalRegisterInput
    export type SignUpMutationError = ErrorType<SignUp409 | SignUp500>

    export const useSignUp = <TError = ErrorType<SignUp409 | SignUp500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError,{data: LocalRegisterInput}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof signUp>>,
        TError,
        {data: LocalRegisterInput},
        TContext
      > => {

      const mutationOptions = getSignUpMutationOptions(options);

      return useMutation(mutationOptions);
    }
