/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IMS API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CountryList200Item,
  CreateOrganization201,
  CreateOrganization403,
  CreateOrganization409,
  CreateOrganizationBody,
  GetOrganizationById200,
  GetOrganizationById500,
  IsAuthenticated200,
  IsAuthenticated401,
  IsAuthenticated500,
  LocalLoginInput,
  LocalRegisterInput,
  Login200,
  Login400,
  Login401,
  Login500,
  Logout500,
  LogoutBody,
  OrganizationList200,
  OrganizationList500,
  RefreshToken200,
  RefreshToken401,
  RefreshToken500,
  RefreshTokenBody,
  SignUp201,
  SignUp409,
  SignUp500,
  SocialLoginfacebookParams,
  SocialLogingoogleParams,
  StateList200Item,
  StateList500,
  StateListParams,
  UpdateOrganization200,
  UpdateOrganization409,
  UpdateOrganizationBody
} from './model';

import { customInstance } from './mutator/custom-instance';
import type { ErrorType } from './mutator/custom-instance';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const login = (
    localLoginInput: LocalLoginInput,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Login200>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: localLoginInput, signal
    },
      options);
    }
  


export const getLoginMutationOptions = <TError = ErrorType<Login400 | Login401 | Login500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LocalLoginInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LocalLoginInput}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LocalLoginInput}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LocalLoginInput
    export type LoginMutationError = ErrorType<Login400 | Login401 | Login500>

    export const useLogin = <TError = ErrorType<Login400 | Login401 | Login500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LocalLoginInput}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LocalLoginInput},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const signUp = (
    localRegisterInput: LocalRegisterInput,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SignUp201>(
      {url: `/api/auth/sign-up`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: localRegisterInput, signal
    },
      options);
    }
  


export const getSignUpMutationOptions = <TError = ErrorType<SignUp409 | SignUp500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError,{data: LocalRegisterInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError,{data: LocalRegisterInput}, TContext> => {

const mutationKey = ['signUp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signUp>>, {data: LocalRegisterInput}> = (props) => {
          const {data} = props ?? {};

          return  signUp(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignUpMutationResult = NonNullable<Awaited<ReturnType<typeof signUp>>>
    export type SignUpMutationBody = LocalRegisterInput
    export type SignUpMutationError = ErrorType<SignUp409 | SignUp500>

    export const useSignUp = <TError = ErrorType<SignUp409 | SignUp500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError,{data: LocalRegisterInput}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof signUp>>,
        TError,
        {data: LocalRegisterInput},
        TContext
      > => {

      const mutationOptions = getSignUpMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const logout = (
    logoutBody: LogoutBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/api/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: logoutBody, signal
    },
      options);
    }
  


export const getLogoutMutationOptions = <TError = ErrorType<Logout500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: LogoutBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: LogoutBody}, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, {data: LogoutBody}> = (props) => {
          const {data} = props ?? {};

          return  logout(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    export type LogoutMutationBody = LogoutBody
    export type LogoutMutationError = ErrorType<Logout500>

    export const useLogout = <TError = ErrorType<Logout500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: LogoutBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        {data: LogoutBody},
        TContext
      > => {

      const mutationOptions = getLogoutMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const refreshToken = (
    refreshTokenBody: RefreshTokenBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RefreshToken200>(
      {url: `/api/auth/token/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenBody, signal
    },
      options);
    }
  


export const getRefreshTokenMutationOptions = <TError = ErrorType<RefreshToken401 | RefreshToken500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshTokenBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshTokenBody}, TContext> => {

const mutationKey = ['refreshToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshToken>>, {data: RefreshTokenBody}> = (props) => {
          const {data} = props ?? {};

          return  refreshToken(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>
    export type RefreshTokenMutationBody = RefreshTokenBody
    export type RefreshTokenMutationError = ErrorType<RefreshToken401 | RefreshToken500>

    export const useRefreshToken = <TError = ErrorType<RefreshToken401 | RefreshToken500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshTokenBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof refreshToken>>,
        TError,
        {data: RefreshTokenBody},
        TContext
      > => {

      const mutationOptions = getRefreshTokenMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const socialLogingoogle = (
    params: SocialLogingoogleParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/google`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getSocialLogingoogleQueryKey = (params?: SocialLogingoogleParams,) => {
    return [
    `/api/auth/google`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSocialLogingoogleQueryOptions = <TData = Awaited<ReturnType<typeof socialLogingoogle>>, TError = ErrorType<void>>(params: SocialLogingoogleParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof socialLogingoogle>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSocialLogingoogleQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof socialLogingoogle>>> = ({ signal }) => socialLogingoogle(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof socialLogingoogle>>, TError, TData> & { queryKey: QueryKey }
}

export type SocialLogingoogleQueryResult = NonNullable<Awaited<ReturnType<typeof socialLogingoogle>>>
export type SocialLogingoogleQueryError = ErrorType<void>



export function useSocialLogingoogle<TData = Awaited<ReturnType<typeof socialLogingoogle>>, TError = ErrorType<void>>(
 params: SocialLogingoogleParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof socialLogingoogle>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSocialLogingoogleQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const socialLoginfacebook = (
    params: SocialLoginfacebookParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/facebook`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getSocialLoginfacebookQueryKey = (params?: SocialLoginfacebookParams,) => {
    return [
    `/api/auth/facebook`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSocialLoginfacebookQueryOptions = <TData = Awaited<ReturnType<typeof socialLoginfacebook>>, TError = ErrorType<void>>(params: SocialLoginfacebookParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof socialLoginfacebook>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSocialLoginfacebookQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof socialLoginfacebook>>> = ({ signal }) => socialLoginfacebook(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof socialLoginfacebook>>, TError, TData> & { queryKey: QueryKey }
}

export type SocialLoginfacebookQueryResult = NonNullable<Awaited<ReturnType<typeof socialLoginfacebook>>>
export type SocialLoginfacebookQueryError = ErrorType<void>



export function useSocialLoginfacebook<TData = Awaited<ReturnType<typeof socialLoginfacebook>>, TError = ErrorType<void>>(
 params: SocialLoginfacebookParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof socialLoginfacebook>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSocialLoginfacebookQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const isAuthenticated = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<IsAuthenticated200>(
      {url: `/api/auth/is-authenticated`, method: 'GET', signal
    },
      options);
    }
  



export const getIsAuthenticatedQueryKey = () => {
    return [
    `/api/auth/is-authenticated`
    ] as const;
    }

    
export const getIsAuthenticatedQueryOptions = <TData = Awaited<ReturnType<typeof isAuthenticated>>, TError = ErrorType<IsAuthenticated401 | IsAuthenticated500>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof isAuthenticated>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getIsAuthenticatedQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof isAuthenticated>>> = ({ signal }) => isAuthenticated(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof isAuthenticated>>, TError, TData> & { queryKey: QueryKey }
}

export type IsAuthenticatedQueryResult = NonNullable<Awaited<ReturnType<typeof isAuthenticated>>>
export type IsAuthenticatedQueryError = ErrorType<IsAuthenticated401 | IsAuthenticated500>



export function useIsAuthenticated<TData = Awaited<ReturnType<typeof isAuthenticated>>, TError = ErrorType<IsAuthenticated401 | IsAuthenticated500>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof isAuthenticated>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getIsAuthenticatedQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const createOrganization = (
    createOrganizationBody: CreateOrganizationBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateOrganization201>(
      {url: `/api/organizations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOrganizationBody, signal
    },
      options);
    }
  


export const getCreateOrganizationMutationOptions = <TError = ErrorType<CreateOrganization403 | CreateOrganization409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{data: CreateOrganizationBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{data: CreateOrganizationBody}, TContext> => {

const mutationKey = ['createOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrganization>>, {data: CreateOrganizationBody}> = (props) => {
          const {data} = props ?? {};

          return  createOrganization(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof createOrganization>>>
    export type CreateOrganizationMutationBody = CreateOrganizationBody
    export type CreateOrganizationMutationError = ErrorType<CreateOrganization403 | CreateOrganization409>

    export const useCreateOrganization = <TError = ErrorType<CreateOrganization403 | CreateOrganization409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{data: CreateOrganizationBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createOrganization>>,
        TError,
        {data: CreateOrganizationBody},
        TContext
      > => {

      const mutationOptions = getCreateOrganizationMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const organizationList = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrganizationList200>(
      {url: `/api/organizations`, method: 'GET', signal
    },
      options);
    }
  



export const getOrganizationListQueryKey = () => {
    return [
    `/api/organizations`
    ] as const;
    }

    
export const getOrganizationListQueryOptions = <TData = Awaited<ReturnType<typeof organizationList>>, TError = ErrorType<OrganizationList500>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof organizationList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationList>>> = ({ signal }) => organizationList(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationList>>, TError, TData> & { queryKey: QueryKey }
}

export type OrganizationListQueryResult = NonNullable<Awaited<ReturnType<typeof organizationList>>>
export type OrganizationListQueryError = ErrorType<OrganizationList500>



export function useOrganizationList<TData = Awaited<ReturnType<typeof organizationList>>, TError = ErrorType<OrganizationList500>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof organizationList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getOrganizationListQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getOrganizationById = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetOrganizationById200>(
      {url: `/api/organizations/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetOrganizationByIdQueryKey = (id?: string,) => {
    return [
    `/api/organizations/${id}`
    ] as const;
    }

    
export const getGetOrganizationByIdQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizationById>>, TError = ErrorType<GetOrganizationById500>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizationById>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationById>>> = ({ signal }) => getOrganizationById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganizationById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOrganizationByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationById>>>
export type GetOrganizationByIdQueryError = ErrorType<GetOrganizationById500>



export function useGetOrganizationById<TData = Awaited<ReturnType<typeof getOrganizationById>>, TError = ErrorType<GetOrganizationById500>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizationById>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetOrganizationByIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const updateOrganization = (
    id: string,
    updateOrganizationBody: UpdateOrganizationBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdateOrganization200>(
      {url: `/api/organizations/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateOrganizationBody
    },
      options);
    }
  


export const getUpdateOrganizationMutationOptions = <TError = ErrorType<UpdateOrganization409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganization>>, TError,{id: string;data: UpdateOrganizationBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateOrganization>>, TError,{id: string;data: UpdateOrganizationBody}, TContext> => {

const mutationKey = ['updateOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrganization>>, {id: string;data: UpdateOrganizationBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOrganization(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrganization>>>
    export type UpdateOrganizationMutationBody = UpdateOrganizationBody
    export type UpdateOrganizationMutationError = ErrorType<UpdateOrganization409>

    export const useUpdateOrganization = <TError = ErrorType<UpdateOrganization409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganization>>, TError,{id: string;data: UpdateOrganizationBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateOrganization>>,
        TError,
        {id: string;data: UpdateOrganizationBody},
        TContext
      > => {

      const mutationOptions = getUpdateOrganizationMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const countryList = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CountryList200Item[]>(
      {url: `/api/region/countries`, method: 'GET', signal
    },
      options);
    }
  



export const getCountryListQueryKey = () => {
    return [
    `/api/region/countries`
    ] as const;
    }

    
export const getCountryListQueryOptions = <TData = Awaited<ReturnType<typeof countryList>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof countryList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCountryListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof countryList>>> = ({ signal }) => countryList(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof countryList>>, TError, TData> & { queryKey: QueryKey }
}

export type CountryListQueryResult = NonNullable<Awaited<ReturnType<typeof countryList>>>
export type CountryListQueryError = ErrorType<unknown>



export function useCountryList<TData = Awaited<ReturnType<typeof countryList>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof countryList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCountryListQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const stateList = (
    params: StateListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StateList200Item[]>(
      {url: `/api/region/states`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getStateListQueryKey = (params?: StateListParams,) => {
    return [
    `/api/region/states`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStateListQueryOptions = <TData = Awaited<ReturnType<typeof stateList>>, TError = ErrorType<void | StateList500>>(params: StateListParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof stateList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStateListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof stateList>>> = ({ signal }) => stateList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof stateList>>, TError, TData> & { queryKey: QueryKey }
}

export type StateListQueryResult = NonNullable<Awaited<ReturnType<typeof stateList>>>
export type StateListQueryError = ErrorType<void | StateList500>



export function useStateList<TData = Awaited<ReturnType<typeof stateList>>, TError = ErrorType<void | StateList500>>(
 params: StateListParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof stateList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getStateListQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
